services:
  - type: web
    name: gestion-laravel
    env: php
    plan: free
    region: frankfurt
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: 57415
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: DFlhLfDlrJgHVgpnyIHFFaATdGAOeFXS
